# Railway deployment configuration
# Deploy RSS proxy to Railway's managed platform

# railway.toml
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node standalone-proxy-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3001"

# To deploy:
# 1. Install Railway CLI: npm install -g @railway/cli
# 2. Login: railway login
# 3. Create project: railway new
# 4. Deploy: railway up
