name: WTTP Deployment

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'contracts/**'
      - 'scripts/wttp-**'
      - 'package.json'
      - '.env.example'
  workflow_dispatch:
    inputs:
      deploy_type:
        description: 'Deployment type'
        required: true
        default: 'content'
        type: choice
        options:
        - 'content'
        - 'contract'
        - 'full'
      network:
        description: 'Network to deploy to'
        required: true
        default: 'sepolia'
        type: choice
        options:
        - 'sepolia'
        - 'mainnet'

env:
  NODE_VERSION: '18'

jobs:
  test:
    name: Test Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install WTTP dependencies
      run: npm run wttp:install
      
    - name: Run tests
      run: npm test
      
    - name: Build application
      run: npm run build
      
    - name: Prepare WTTP content
      run: node scripts/wttp-prepare-content.js
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wttp-build-${{ github.sha }}
        path: |
          dist/
          wttp-content/
        retention-days: 7

  deploy-contract:
    name: Deploy WTTP Contract
    runs-on: ubuntu-latest
    needs: test
    if: github.event.inputs.deploy_type == 'contract' || github.event.inputs.deploy_type == 'full' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    
    environment: 
      name: ${{ github.event.inputs.network || 'sepolia' }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install WTTP dependencies
      run: npm run wttp:install
      
    - name: Compile contracts
      run: npm run wttp:compile
      
    - name: Deploy WTTP site contract
      env:
        WTTP_PRIVATE_KEY: ${{ secrets.WTTP_PRIVATE_KEY }}
        WTTP_NETWORK: ${{ github.event.inputs.network || 'sepolia' }}
        WTTP_RPC_URL: ${{ secrets.WTTP_RPC_URL }}
      run: npm run wttp:deploy-contract
      
    - name: Save deployment info
      uses: actions/upload-artifact@v4
      with:
        name: wttp-deployment-${{ github.sha }}
        path: |
          wttp-deployments/
        retention-days: 30

  deploy-content:
    name: Deploy WTTP Content
    runs-on: ubuntu-latest
    needs: [test, deploy-contract]
    if: always() && (needs.test.result == 'success') && (needs.deploy-contract.result == 'success' || needs.deploy-contract.result == 'skipped')
    
    environment:
      name: ${{ github.event.inputs.network || 'sepolia' }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install WTTP dependencies
      run: npm run wttp:install
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: wttp-build-${{ github.sha }}
        
    - name: Deploy content to WTTP
      env:
        WTTP_SITE_ADDRESS: ${{ secrets.WTTP_SITE_ADDRESS }}
        WTTP_PRIVATE_KEY: ${{ secrets.WTTP_PRIVATE_KEY }}
        WTTP_NETWORK: ${{ github.event.inputs.network || 'sepolia' }}
      run: npm run wttp:deploy-content
      
    - name: Test WTTP deployment
      env:
        WTTP_SITE_ADDRESS: ${{ secrets.WTTP_SITE_ADDRESS }}
      run: npm run wttp:test
      continue-on-error: true

  deploy-content-only:
    name: Deploy Content Only
    runs-on: ubuntu-latest
    needs: test
    if: github.event.inputs.deploy_type == 'content'
    
    environment:
      name: ${{ github.event.inputs.network || 'sepolia' }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install WTTP dependencies
      run: npm run wttp:install
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: wttp-build-${{ github.sha }}
        
    - name: Deploy content to WTTP
      env:
        WTTP_SITE_ADDRESS: ${{ secrets.WTTP_SITE_ADDRESS }}
        WTTP_PRIVATE_KEY: ${{ secrets.WTTP_PRIVATE_KEY }}
        WTTP_NETWORK: ${{ github.event.inputs.network || 'sepolia' }}
      run: npm run wttp:deploy-content
      
    - name: Test WTTP deployment
      env:
        WTTP_SITE_ADDRESS: ${{ secrets.WTTP_SITE_ADDRESS }}
      run: npm run wttp:test

  notify:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [deploy-contract, deploy-content, deploy-content-only]
    if: always()
    
    steps:
    - name: Deployment Success
      if: needs.deploy-content.result == 'success' || needs.deploy-content-only.result == 'success'
      run: |
        echo "🎉 WTTP deployment completed successfully!"
        echo "Site URL: wttp://${{ secrets.WTTP_SITE_ADDRESS }}/"
        
    - name: Deployment Failure
      if: needs.deploy-content.result == 'failure' || needs.deploy-content-only.result == 'failure' || needs.deploy-contract.result == 'failure'
      run: |
        echo "❌ WTTP deployment failed!"
        echo "Check the logs above for details."
        exit 1
